name: Update GCP Custom Constraints
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrape GCP custom constraints
        run: python scrape_gcp_custom_constraints.py
      - name: Commit changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add custom_constraints.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update GuardDuty findings"
            git push
          fi
